name: Build TWRP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bison build-essential ccache cmake flex g++-multilib git-lfs lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

    - name: Initialize TWRP environment
      run: |
        git clone https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-11.0 .repo/local_manifests
        repo sync

    - name: Build TWRP
      run: |
        . build/envsetup.sh
        lunch omni_lancelot-eng
        mka recoveryimage
